spring:
  datasource:
    url: jdbc:mysql://dev.ftq.ink:3306/ftq_pay?useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: 3kk67RYnL6UtZjU
  redis:
    host: dev.ftq.ink
    port: 6379
    password: 3kk67RYnL6UtZjU # 如果没有密码可以省略
    database: 0
server:
  hostname: dev.ftq.ink